### ISSUE TITLE
README Typo

### ISSUE THREAD

**Issue by ChristmasTaco** [vmware-tanzu-learning/tko-ref-arch-training#1]
<img width="820" alt="README_-_TKO__Beyond_the_CKA_-_KubeAcademy" src="https://user-images.githubusercontent.com/12519848/160666554-b93fcc3b-3945-4260-9926-76c9cdceb30d.png">

The word 'message' is misspelled.

**Comment by djschny** [comment]
Fixed - https://admin.staging.kubeacademy.fixeldev.com/courses/tko-01-beyond-cka/lessons/README
