### ISSUE TITLE
research lab environment options

### ISSUE THREAD

**Issue by djschny** [vmware-tanzu-learning/tko-ref-arch-training#11]
As we continue to move towards TKO Ref Arch installations, lab environments will be be needed. They will fall into two categories:

* One with IaaS to build solutions
* One with solution already installed/configured

**Comment by ndwinton** [comment]
We can't demonstrate all of the features of TCE/TKG with Kind-based clusters.

We need some kind of AWS, Azure or vSphere environment with sufficient student access (but instructor control!) to allow a full demonstration of the available capabilities, e.g. ClusterAPI, OIDC integration etc. In the future the [Bring Your Own Host](https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost) (BYOH) ClusterAPI work might help in a Strigo environment, but would need TCE integration.

A HOL-style vApp might be possible, but integration with external elements (e.g. Let's Encrypt, Okta) would be a challenge.

**Comment by hosseinpn** [comment]
The research was done.
