### ISSUE TITLE
include way for learners to provide feedback

### ISSUE THREAD

**Issue by djschny** [vmware-tanzu-learning/tko-ref-arch-training#13]
As [discussed in Slack](https://vmware.slack.com/archives/C030C4T6HEJ/p1645812379914159?thread_ts=1645719274.306259&cid=C030C4T6HEJ) , generate some questions to guide feedback of the first round of TKO training. For example:

* For each course in the learning path, please rate it from the following to perspectives please:
  * Course in General
  * Course specifically in regards to helpful in preparing you to use and build TKO Reference Architecture solutions
* For each course in the learning path, please provide any open and general feedback
* The following additional content is planned on being added to the training to continue learning before using the TKO Deployment Guides. Is there anything you feel should be part of it that is not there, or a different angle missing?
  * Harbor will be setup and configured to work with clusters like TCE 
  * TMC with TCE
  * TKO common concepts
  * Lab to deploy TKO on AWS

**Comment by djschny** [comment]
cc @carolynhaines

**Comment by hosseinpn** [comment]
Not relevant to live public courses
