### ISSUE TITLE
Review alignment of TCE and TKG versions

### ISSUE THREAD

**Issue by ndwinton** [vmware-tanzu-learning/tko-ref-arch-training#15]
**Why would you like this feature?**
The current published version of the deployment guide for TKO on AWS uses TKG 1.4. TCE is a more "bleeding edge" package of components. As such the versions of software available are in some cases ahead of those that are included in TKG (and hence TKO). This is certainly the case for TKG 1.4, and may be the case for TKG 1.5 too.

**Describe what you'd like to see**
* Clear understanding of any potential issues
* Agreed position on target reference architecture version.
* Strategy for evolution going forward.

**Comment by hosseinpn** [comment]
TCE is paused!
