### ISSUE TITLE
Please update our Slack channel in the KA LP description to #tanzu_learning_tko_training

### ISSUE THREAD

**Issue by ChristmasTaco** [vmware-tanzu-learning/tko-ref-arch-training#17]
**Describe the issue**
A clear and concise description of what the problem is.

I updated our trainee Slack channel to reflect the actual name of our team, but didn't acknowledge at the time that we'll need to update it in KubeAcademy. Please update the description in the learning path to reflect the new Slack channel name.

**Comment by ChristmasTaco** [comment]
It's shown on the top level description at https://staging.kubeacademy.fixeldev.com/paths/tanzu-kubernetes-operations.

![Uploading Tanzu_Kubernetes_Operations_-_KubeAcademy.png…]()

**Comment by djschny** [comment]
This has been updated. I also updated it in the two lessons in the following course in the path:

https://staging.kubeacademy.fixeldev.com/courses/tko-deploy-a-tko-reference-architecture
