### ISSUE TITLE
Need some changes to the "Deploy a TKO reference architecture" Course

### ISSUE THREAD

**Issue by ChristmasTaco** [vmware-tanzu-learning/tko-ref-arch-training#18]
**Describe the issue**
In the first lesson in this final course, we have some changes to the actual deployment process given some limitations we've discovered with the pcf-practices org. Here is the desired copy for the 'Overview and Prep' Lesson:

"Currently the IaaS solution available for deploying the TKO Ref Arch is AWS. You will need to request access to an AWS account, which can be done [here](https://servicedesk.eng.vmware.com/servicedesk/customer/portal/3/create/338). Follow the instructions in the image below to ensure your request gets granted:

<img width="589" alt="AWS_Account_Creation_Request__Commercial__-_Common_SaaS_Service_Desk_-_Service_Desk" src="https://user-images.githubusercontent.com/12519848/162086045-4cbbeaf5-c151-4f99-b95c-630ec5dd0f46.png">

Once your request is granted, you will receive an email with instructions on how to access your account. Feel free to pair up ad hoc if you'd like to work with someone else in the training who has also completed the KubeAcademy course. 

Next, review the [Deploy Tanzu for Kubernetes Operations on AWS](https://docs.vmware.com/en/VMware-Tanzu/services/tanzu-reference-architecture/GUID-deployment-guides-tko-aws.html) documentation. You may also view the same deployment guide on [Github](https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/blob/main/src/deployment-guides/tko-aws.md), which is where you may also submit feedback/issues that you have on the guide.

You have already been granted access to all of our SaaS products, so please visit the following links to view the SaaS products.

SAAS ACCESS: Be sure to select the “MAPBU Platform Services Org” for TMC and TSM
[Tanzu Mission Control (TMC)](https://tanzueducation.tmc.cloud.vmware.com/clusters)
***[TMC Alternate link (if you get an error)](https://vplpsamer.tmc.cloud.vmware.com/clusters)
Note: PLEASE name any clusters you create with your Initials. We have many people using the same TMC console, so this will help ensure we don’t step on one another…
[Tanzu Observability (TO)](https://vmware.wavefront.com/dashboards)
[Tanzu Service Mesh (TSM)](https://prod-2.nsxservicemesh.vmware.com/home?view=global-namespaces)

Product feedback on any of the above should be entered into the appropriate channel for each product:
#tmc-product
#tobs-product
#tsm-product

In the next lesson you'll actually start working through the deployment, and for any questions please reach out to us in our training Slack channel #tanzu_learning_tko_training"

**To reproduce**
1. Go to 'https://staging.kubeacademy.fixeldev.com/courses/tko-deploy-a-tko-reference-architecture/lessons/overview-and-prep'

**Comment by djschny** [comment]
@ChristmasTaco I've updated it. Please take a look and if it looks good please close this issue. I added some extra bullets and formatting, hopefully looks OK.

**Comment by djschny** [comment]
Closing as assumed OK now
