### ISSUE TITLE
Inclusion of Sonobuoy

### ISSUE THREAD

**Issue by ndwinton** [vmware-tanzu-learning/tko-ref-arch-training#19]
**Why would you like this feature?**
[Sononbuoy](https://sonobuoy.io/) doesn't get much attention, but it's a part of TCE/TKG and integrates into TMC. 

**Describe what you'd like to see**
A lab on the use and interpretation of Sonobuoy reports. Possibly including adding something custom too.

**Comment by djschny** [comment]
We could look into adding it as part of the Cluster Ops (Kubernetes Platform Design) course and have it installed and run in the `kubeadm` cluster that was built?

**Comment by mrporcles** [comment]
@djschny @ndwinton where in the course do we think is a good fit for this module?:

- Last step in 1. Cluster Setup - To demonstrate cluster conformance to upstream or CIS benchmark for instance for newly built cluster
- 4. Cluster troubleshooting - As an extra tool to identify cluster issues using specific plugin
- 6. Cluster maintenance - Regular tests to identify cluster conformance or UAC conformance for instance

I like the idea of 1. Cluster Setup as the CIS benchmark runs very quickly and would most likely be a recommended part of the workflow in standing up a new cluster

**Comment by ndwinton** [comment]
It could be added to the existing course, and that might be the best place for it. However, we were originally thinking of this as a module in a new course that covers other things like service mesh. If it's in the new course, then it makes sense to do it very early, because a new cluster will be created as part of that. It would be good to have Sonobuoy runs repeated later, for example after service mesh installation, to verify that things are still conformant.

**Comment by mrporcles** [comment]
> It could be added to the existing course, and that might be the best place for it. However, we were originally thinking of this as a module in a new course that covers other things like service mesh. If it's in the new course, then it makes sense to do it very early, because a new cluster will be created as part of that. It would be good to have Sonobuoy runs repeated later, for example after service mesh installation, to verify that things are still conformant.

Ok. I was just basing my thoughts on the comment above regards it being added as part of the Cluster Ops course as I do envisage it being a relatively small module. So then I guess the follow up question is what is the consensus for where this belongs (current or new)?

**Comment by djschny** [comment]
See https://github.com/vmware-tanzu-learning/tko-ref-arch-training/issues/12#issuecomment-1148635979 for the original outlines put together and the rest of the issue for details.

> where in the course do we think is a good fit for this module?

The current thought was it is introduced in the first lecture/lab.

>  I do envisage it being a relatively small module

What is your definition of `module`? In this situation the lecture component will probably be very small, but the lab component will require quite a bit and most likely spread across various labs.

**Comment by mrporcles** [comment]
@djschny 

> The current thought was it is introduced in the first lecture/lab.

The first lecture lab in the new course or current Cluster Ops course?

> What is your definition of module? In this situation the lecture component will probably be very small, but the lab component will require quite a bit and most likely spread across various labs.

By module I just mean grouping of content. Why do you envisage the lab bit to be big? Standard conformance will take too long to run so running after every addition is a non starter really. I advise running the CSI benchmark plugin/monitoring status and analysing results. This all takes about 5 min. So we can talk about the e2e plugin and why its important but not actually run it. Security tests/benchmarks are just as important IMO. Maybe I'm missing something?

- Overview
- Download cli tool
- Run scan using plugin
- Retrieve and analyse results
- Maybe write custom test? Scan/Results
- Remove sonobuoy objects from cluster

**Comment by djschny** [comment]
> The first lecture lab in the new course or current Cluster Ops course?

The new course.

> By module I just mean grouping of content. Why do you envisage the lab bit to be big? 

The explanation of it and it's details, the running of it, interpreting results, crafting a lab where it is run and we intentional make it report on something that is wrong, then fix it and rerun, etc.

**Comment by mrporcles** [comment]
@ndwinton @djschny Lab material is ready for review under the [sonobuoy branch](https://github.com/vmware-tanzu-learning/k8s-platform-design-extended/tree/sonobuoy)

**Comment by ndwinton** [comment]
@mrporcles - It looks very good to me, nice job!

Obviously we're missing some of the context that might come in a general discussion of K8s diagnostic tools, that would probably come in the preceding lecture material. It might be good to mention the particular challenges that Sonobuoy was designed to address, such as automatically running tests on every node in a cluster.

There are a few matters of formatting and a shift of voice between paragraphs ("we and our" vs "you and your" - I've tried to stick with the latter, directing the student deliberately), but overall I'd say let's get this PRed/merged in and we can fix those things quite easily.

**Comment by mrporcles** [comment]
Made some minor language changes and submitted [PR](https://github.com/vmware-tanzu-learning/k8s-platform-design-extended/pull/5)

**Comment by mrporcles** [comment]
Lab complete. Separate [issue](https://github.com/vmware-tanzu-learning/k8s-platform-design-extended/issues/4) exists for creation of lecture recordings
