### ISSUE TITLE
Let's add product documentation to the KA LP somewhere

### ISSUE THREAD

**Issue by ChristmasTaco** [vmware-tanzu-learning/tko-ref-arch-training#21]
**Why would you like this feature?**
The only remaining items of interest from the Google Doc training are the links to product docs, etc. I figure it'd be good to have them included _somewhere_ in the KA LP. 

**Describe what you'd like to see**
I'd like the following copy added wherever you feel it would be most relevant, possibly in the last Course when the users are doing the deployment? The below will need some basic formatting.

"Tanzu for Kubernetes Operations (TKO) is a marketing bundle that aims to meet the needs of on-premise and public cloud infrastructure teams.
TKO addresses:
- Developer self-service to the right infrastructure abstraction and app building blocks
- Automation and monitoring of cloud platform operations
- Enforcement of Networking, security and compliance requirements
- Platform operation cost optimization

VMware Internal Bundle Page[ Link](https://confluence.eng.vmware.com/pages/viewpage.action?pageId=1130565069)

- Tanzu Mission Control (TMC) Advanced - Includes additional functionality around policies.
- Tanzu Service Mesh (TSM) Advanced - The base offering of TSM. TSM Enterprise is the upgraded offering providing additional features. See[ Link](https://confluence.eng.vmware.com/pages/viewpage.action?pageId=709524733) highlighting TSM Advanced vs Enterprise editions.
- Antrea Advanced - Offers[ Tier](https://confluence.eng.vmware.com/pages/viewpage.action?spaceKey=NSBU&title=Tiers) RBAC[ policy control](https://vmware.slack.com/archives/CPUHFFJJ2/p1641237810203500?thread_ts=1641234404.203400&cid=CPUHFFJJ2) and Wavefront Integration. See[ Datasheet](https://www.vmware.com/content/dam/digitalmarketing/vmware/en/pdf/products/vmware-container-networking-antrea-datasheet.pdf) for different Antrea offerings and details. See[ tech talk](https://tech-talks.eng.vmware.com/talks/kubernetes-networking-with-project-antrea) on Antrea Networking & Tier RBAC.
- AVI Enterprise (aka AVI Vantage/NSX Advanced Load Balancer) - Full featured L7 Container Ingress with WAF support for On-Premise. See[ Datasheet](https://confluence.eng.vmware.com/display/TKG/AVI+Lite+Integration?preview=%2F748658422%2F805584013%2FFeature-List-Avi-ESSENTIALS-vs-BASIC-vs-ENTERPRISE-For-AKO+%281%29.pdf) for complete feature list and editions comparison.

Product Details Direct Links for reference:
TKG v1.4.1 - Tanzu Kubernetes Grid:
What is it and why is it valuable?
[Solution Brief](https://d1fto35gcfffzn.cloudfront.net/tanzu/tkg/TKG-Solution-Overview.pdf)
Docs (be sure to look at v1.4.1):
[TKG v1.4 Docs](https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.4/vmware-tanzu-kubernetes-grid-14/GUID-index.html)
TMC - Tanzu Mission Control:
What is it and why is it valuable?
[High Level Overview](https://docs.vmware.com/en/VMware-Tanzu-Mission-Control/index.html)
https://docs.vmware.com/en/VMware-Tanzu-Mission-Control/services/tanzumc-concepts/GUID-9E6DEA00-C368-4B06-B93E-BA1916EB2929.html
Docs:
https://docs.vmware.com/en/VMware-Tanzu-Mission-Control/services/tanzumc-using.pdf
TO - Tanzu Observability
What is it and why is it valuable? 
https://www.youtube.com/playlist?list=PLPGZsvbdUCi4UvTy3WLtqfUXw_P-iKLKP
Demo Walkthrough:
Session 1
https://vmware.zoom.us/rec/share/gttOKcM9YDAYz8uK-YbDPgB7jkP9rPCJuErQNMAdgrVtqYjdLsk_cqTPqmiTO_ur.PYprV051Hz-f4IQZ
Access Passcode: 937MDgZ*
Session 2
https://vmware.zoom.us/rec/share/XEjwSMV-HagZs07foV9M4tM6_n5DNnNH6w4p4THgTf19oMC-iRJ85gMAc6Vs1T1_.Qkt0kPNYynP0DLLO
Access Passcode: l&N.n5^m
Docs:
https://docs.wavefront.com/
TSM - Tanzu Service Mesh
What is it and why is it valuable?
https://docs.vmware.com/en/VMware-Tanzu-Service-Mesh/services/concepts-guide/GUID-DEB57BAB-688F-4A4D-81E8-9CECC0F80FD5.html
[Fun write up with examples](https://veducate.co.uk/tanzu-service-mesh-first-look/)
Docs:
https://docs.vmware.com/en/VMware-Tanzu-Service-Mesh/index.html
Ancillary learning about service meshes and ISTIO:
https://www.youtube.com/watch?v=16fgzklcF7Y
https://www.youtube.com/watch?v=voAyroDb6xk&t=1103s
Antrea - container networking:
Docs:
https://docs.vmware.com/en/VMware-Container-Networking-with-Antrea/index.html
Ancillary Learning:
https://www.youtube.com/watch?v=l4Qdltsl01U

Cloud Native Readiness Library
This is a repo of information on various kubernetes concepts/constructs and various products in each. Tons of great stuff in here!
[CNR Library](https://cnr.eng.vmware.com/library/)"

**Comment by djschny** [comment]
This was already migrated as a course within the TKO Learning Path:

https://staging.kubeacademy.fixeldev.com/courses/tanzu-for-kubernetes-operations-tko-products-and-components

**Comment by ChristmasTaco** [comment]
🤦  Thanks! I'll delete
