### ISSUE TITLE
Demonstrate a Kubernetes upgrade in TCE

### ISSUE THREAD

**Issue by ndwinton** [vmware-tanzu-learning/tko-ref-arch-training#22]
**Why would you like this feature?**
This would introduce the Tanzu Kubernetes Release concept and show how TCE/TKG simplifies cluster upgrade

**Describe what you'd like to see**
* List available TKRs with `tanzu kr get`
* Create a new workload cluster with a down-level version
* Scale to 2 workers with `tanzu cluster scale`
* Deploy NGINX
* Upgrade cluster with `tanzu cluster upgrade`

**Describe alternatives you've considered**
* A downgrade of an existing workload cluster is not possible
* A change of OS from (say) Ubuntu to Amazon would be possible for non Docker-based TCE, e.g. `tanzu cluster upgrade tce-work --os-name amazon --os-version 2 --os-arch amd64`

**Comment by hosseinpn** [comment]
We're putting a pause on this one
