### ISSUE TITLE
Add Pinniped configuration

### ISSUE THREAD

**Issue by ndwinton** [vmware-tanzu-learning/tko-ref-arch-training#24]
**Why would you like this feature?**
We want to demonstrate how the Pinniped login integration works. This isn't possible with TCE on Kind but is quite easy to set up using TCE on AWS and an Okta development account.

**Describe what you'd like to see**
* A lab with a TCE/TKG cluster created with Pinniped authentication

**Describe alternatives you've considered**
*According to [this README in the Pinnped add-on source](https://github.com/vmware-tanzu/tanzu-framework/tree/main/addons/pinniped) you can add Pinniped after cluster creation. If MetalLB is added to the TCE/Kind cluster, it might be possible, therefore, to get this to work.

**Comment by bijoych** [comment]
TKG integration with pinniped - https://confluence.eng.vmware.com/display/~kkothapelly/TKG+Integration+with+Pinniped

**Comment by ndwinton** [comment]
Thanks for the link @bijoych, that's a good reference. It would still be nice to be able to do things with TCE on Docker, but we may have to go for the full TCE/TKG on some IaaS to be able to demonstrate things fully.

**Comment by ndwinton** [comment]
Some notes on further research ...

A full Pinniped deployment has both Supervisor and Concierge components. The Supervisor can be used across multiple clusters and handles federation of sign-on across multiple sources. It's also reasonably complex to deploy.

However, it's possible to use Pinniped in "Concierge-only" mode. This takes care of creating `kubeconfig` configurations for a single cluster (with some limitations) and does not require the Pinniped Supervisor. In this mode it can be be used with either webhook or JWT (OIDC) authentication mechanisms. See [this example](https://pinniped.dev/docs/tutorials/concierge-only-demo/) for details of using it with a webhook. There are also details on [using JWT/OIDC].

One disadvantage of the Concierge-only mode with OIDC is that sign-on requires a re-direct back to a localhost address (completely "headless" login needs the Supervisor). We could, however, use a desktop-based Strigo environment to demonstrate this.

**Comment by ndwinton** [comment]
See PR https://github.com/vmware-tanzu-learning/edu-ilt-ops/pull/246

**Comment by djschny** [comment]
I will be testing this this afternoon.
