### ISSUE TITLE
Image replacement request due to AWS account request process change

### ISSUE THREAD

**Issue by ChristmasTaco** [vmware-tanzu-learning/tko-ref-arch-training#25]
**Describe the issue**
We need to update our process for requesting AWS accounts to folks requesting under their own name due to approval inconsistencies. Please update the image at the top of [this page](https://staging.kubeacademy.fixeldev.com/courses/tko-deploy-a-tko-reference-architecture/lessons/overview-and-prep) with the below image:

<img width="551" alt="AWS_Account_Creation_Request__Commercial__-_Common_SaaS_Service_Desk_-_Service_Desk" src="https://user-images.githubusercontent.com/12519848/162478791-30e92489-ad62-4b29-a56b-3455b5e3feee.png">

**Comment by djschny** [comment]
Image updated. Please review if loading OK.

**Comment by ChristmasTaco** [comment]
Good to go
