### ISSUE TITLE
Need to remove @bridget as the interrupt on one page

### ISSUE THREAD

**Issue by ChristmasTaco** [vmware-tanzu-learning/tko-ref-arch-training#28]
**Describe the issue**
We still suggest reaching out to @bridget as the interrupt engineer on [this page](https://staging.kubeacademy.fixeldev.com/courses/tko-deploy-a-tko-reference-architecture/lessons/deploy-tko-on-aws)

Let's remove the "If no response in 4 hours, reach out to @bridget ([Bridget Arthur](mailto:barthur@vmware.com)) on Slack" bullet.

**Comment by djschny** [comment]
It has been removed.
