### ISSUE TITLE
"Terminate Session" navigates to Edukates login screen

### ISSUE THREAD

**Issue by ChristmasTaco** [vmware-tanzu-learning/tko-ref-arch-training#3]
In our Readme, we suggest users hit 'Terminate Session' at the end of each Lab. This directs me away from KubeAcademy to a login page for Edukates. Is this a necessary step to manage resources used, or something that is not necessary once you navigate away from the Lab Lesson? Just trying to learn.

**Comment by djschny** [comment]
We found out about this earlier this month actually when a KubeAcademy learner reported it.

> The content so far is great! One suggestion I have is that you include a button at the end of lab one and two that terminates the session and directs the student to the next lesson.
>
> The lab can be terminated using the hamburger menu option, which will update the status tile to show complete, but there weren’t any instructions directing me to do that. At first, I instinctively clicked on the Lesson 02: Kubernetes Fundamentals tile which reset my progress in the lab."
>
> Terminating the session is the only way I found to update the status tile on the progress menu.

Unfortunately it's not ideal, but needed for now.
