### ISSUE TITLE
2: Logging, section 2.5.4: Inspect the audit log - missing screenshot

### ISSUE THREAD

**Issue by bstein2379** [vmware-tanzu-learning/tko-ref-arch-training#34]
**Describe the issue:**
In Lab 2: Logging, section 2.5.4: Inspect the audit log, there is a screenshot missing or the text should be reworded.

**To reproduce:**
View the docs URL:   https://{redacted}.rp.strigo.io/instructions/lab02/lab02.html#inspect-the-audit-log

The text assumes there is something to follow, but there is nothing...
"Notice the detailed information about API, user, group, etc., along with HTTP return status (200 for success, 403 for failed authorization, etc.) **on the following line."**

**Expected behavior:**
There should be an example screenshot showing the user an expected output of what it should look like. Or perhaps reword the sentence to: 
"Notice the detailed information about API, user, group, etc., along with HTTP return status (200 for success, 403 for failed authorization, etc.) in your terminal output."

**Screenshots:**
![Screen Shot 2022-04-28 at 10 29 43 AM](https://user-images.githubusercontent.com/37446653/165776460-6280cd21-9dcf-4cc9-8558-58f49d70941d.png)

**Comment by djschny** [comment]
Thanks for reporting this! Will work on a fix.

**Comment by ndwinton** [comment]
Actually, the lab text was correct and there wasn't a missing screenshot. If you look closely is uses `grep -A 1` which means "find the line matching _and also print 1 line of context after it_. So when it said "on the following line" it meant "on the line following the one that matched the pattern". Having said all that, it was obviously confusing so adding an example is obviously a good thing to do!

**Comment by djschny** [comment]
This lab has been updated. New labs launched will use version `v2.4.0-beta10` of the lab instructions and will look like the following:

<img width="781" alt="Screen Shot 2022-05-04 at 8 04 02 AM" src="https://user-images.githubusercontent.com/129643/166677709-37167220-a352-4778-b690-e8684f1c6ff7.png">
<img width="769" alt="Screen Shot 2022-05-04 at 8 04 09 AM" src="https://user-images.githubusercontent.com/129643/166677704-4933b027-0c45-4915-b3bf-8258553def45.png">
