### ISSUE TITLE
update recordings of Kubernetes Platform Design course

### ISSUE THREAD

**Issue by djschny** [vmware-tanzu-learning/tko-ref-arch-training#35]
The `Kubernetes Platform Design` course has outdated recordings not suitable for public consumption. Update the recordings.

**Comment by djschny** [comment]
This has been started this week.

**Comment by djschny** [comment]
After further discussion last week we decided to split up the recordings:

* @djschny - 0, 1, 2, 5, 6
* @ndwinton - 3, 4, 7

Recording drafts and rough cuts are being added to [Google Drive](https://drive.google.com/drive/folders/1vERMLXDMkSO4ey9ZJk2CAzKWr0cHGPRp).

I've requested the new "bumpers" from marketing that gets added at the beginning and end of each video.

**Comment by ndwinton** [comment]
Lectures 3, 4 & 7 went live (in KA staging) a few weeks ago.

@djschny recorded the other sessions but suffered video editing problems. Lecture 1 may need to be redone in the light of the Pinniped changes in lab 5.

**Comment by djschny** [comment]
Lab 01 needs to have slides updated and re-recorded to support Pinniped.

**Comment by mrporcles** [comment]
Picking this up to edit video for 2,5 and 6 using the bumpers located [here](https://drive.google.com/drive/folders/17IKIE4gdvp26ls4s3tcZJSgoMb6P0Q1T)

**Comment by mrporcles** [comment]
Can someone give me write access to the Google Drive to upload the edited versions?

**Comment by djschny** [comment]
> Can someone give me write access to the Google Drive to upload the edited versions?

You should be set. I applied it at a higher level folder as well.

**Comment by djschny** [comment]
Awesome.

The videos for 2, 5, 6 have been updated in Vimeo and should be showing up in the course on KubeAcademy staging.

**Comment by mrporcles** [comment]
Confirmed. I corrected the lesson lengths to reflect the new video lengths for all new uploads. Will return this to the backlog for when you are ready to work on 1 @djschny

**Comment by djschny** [comment]
Slides updated to remove reference to DEX and include pinniped diagram:

![Screen Shot 2022-09-13 at 9 27 17 AM](https://user-images.githubusercontent.com/129643/189913437-302a3b7e-1a07-41fb-9a48-0687623d191b.png)

Next steps:

* Update PSP slides
* Record chapter 1
* Record chapter 5

**Comment by ndwinton** [comment]
Edited videos for lessons 1 and 5 uploaded to Vimeo, along with PDF of slides to Strigo.
