### ISSUE TITLE
"TKGS for TKGM users" content

### ISSUE THREAD

**Issue by ndwinton** [vmware-tanzu-learning/tko-ref-arch-training#36]
**Why would you like this feature?**
While TKGS (aka vSphere with Tanzu) shares many of the same concepts as TKGM, it is sufficiently different that there can be issues in attempting to apply the same approaches in both environments.

This was highlighted in conversation with Sean Pines and Caleb Washburn.

**Describe what you'd like to see**
A tutorial/module/guide of "TKGS for TKGM users" outlining the main similarities and differences, highlighting potential issues and "gotchas"

**Describe alternatives you've considered**
Such a guide may already exist, in which case we should reference it if it can be found

**Comment by bijoych** [comment]
Some of the contents regarding the TKG comparisons as follows:
1. https://confluence.eng.vmware.com/display/CNA/TKG+Comparisons
2. vSphere Pod vs TKG-S vs TKG-M - https://confluence.eng.vmware.com/display/SGSE/vSphere+Pod+vs+TKG-S+vs+TKG-M

**Comment by mrporcles** [comment]
Have written and summarised the content [here](https://gitlab.eng.vmware.com/pwiggett/scratchpad/-/blob/main/tkgs-vs-tkgm.md). Will use this as a basis to create a short video explanation.

**Comment by djschny** [comment]
Awesome @bijoych and @mrporcles. Any reason why we can't take the above mentioned references and summarize them together publicly in one of the following potential ways?

* Body/Description in a lesson in KA
* Markdown committed into this repo or another one and then referenced from a lesson in KA

**Comment by matt79a** [comment]
Additional content regarding TKG comparisons: [](https://confluence.eng.vmware.com/x/BZGDIw )

**Comment by mrporcles** [comment]
Would it make sense to add the comparison overview bits to the `Product: Tanzu Kubernetes Grid (TKG) lesson` and then link out to the detailed comparison tables?

Any ideas on where the best place would be to commit markdown source? I thought the [tko-ref-arch-training](https://github.com/vmware-tanzu-learning/tko-ref-arch-training) repo was only for capturing issues according to its landing page?

**Comment by djschny** [comment]
> Any reason why we can't take the above mentioned references and summarize them together publicly in one of the following potential ways?

Does this most recent comment mean that the answer to the above question is `"No"`?

> Any ideas on where the best place would be to commit markdown source?

Some options can be:

1. put the markdown in the body/description field of the actual lesson in KA.
1. the ideal thing is there is a repo per course. As you call out this repo will eventually go away and be replaced by project boards in github. However lacking all that yet it could be committed to this repo temporarily and then linked and an issue put in place to move it once we reshuffle things.
1. PDF'd and then linked


> I thought the [tko-ref-arch-training](https://github.com/vmware-tanzu-learning/tko-ref-arch-training) repo was only for capturing issues according to its landing page?

Correct yes, we are in a transitive state right now. But can commit to this repo temporarily and we can cleanup later once things have progressed.

**Comment by mrporcles** [comment]
> Does this most recent comment mean that the answer to the above question is "No"?

No. The summary doc I created already includes relevant content from all the suggested links that I think is not too detailed and can also be made publicly available so I would like to use that as the primary source for the course as it provides just the right level of detail IMO.

The md tables don't look great when rendered in a KA lesson hence my suggestion to add the high level comparison bits to the existing lesson and then a link out to the detailed comparison tables if student wishes to get further information

**Comment by mrporcles** [comment]
Mock-up on suggestion above to add comparison overview bits to the ``Product: Tanzu Kubernetes Grid (TKG)`` lesson and then link out to the detailed comparison tables?

![Image](https://user-images.githubusercontent.com/8677171/177534242-d88b9c78-ea1d-40d8-b6b4-a5765f65c476.png)

@djschny @ndwinton happy to move forward with this approach?

**Comment by ndwinton** [comment]
That looks reasonable to me

**Comment by djschny** [comment]
Sure looks great. Once KA is enhanced to have formal body content we can move it there. This works for the interim.

**Comment by mrporcles** [comment]
KA lesson updated with overview bots. Waiting on PR https://github.com/vmware-tanzu-learning/tko-ref-arch-training/pull/56 review so link can be added to detailed breakdown document which will be added to this repo

**Comment by djschny** [comment]
PR has been merged.

**Comment by mrporcles** [comment]
Thanks @djschny - New lesson content with added link available [here](https://staging.kubeacademy.fixeldev.com/courses/tanzu-for-kubernetes-operations-tko-products-and-components/lessons/component-tanzu-kubernetes-grid-tkg)
