### ISSUE TITLE
TCE 0.12 is now GA - check for applicability and viability of current lesson

### ISSUE THREAD

**Issue by ndwinton** [vmware-tanzu-learning/tko-ref-arch-training#37]
**Why would you like this feature?**
The latest version of TCE is now 0.12, which contains substantial new functionality. We need to check first that the current lesson material works in the same way (the 0.11 artefacts still remain in place at the current URLs etc.) and then whether we want to introduce any other functionality from this version.

**Describe what you'd like to see**
Check if the lab still works now that TCE 0.12 is available and upgrade of material, where necessary.

**Comment by ndwinton** [comment]
The 0.11-based lab still works.

There appear to be issues if the workload cluster is created immediately after the management cluster (without any intervening `kubectl` commands being run). This may be a timing issue or, it is seeming more likely, something related to the [discovery cache](https://jonnylangefeld.com/blog/the-kubernetes-discovery-cache-blessing-and-curse). These issues also affect 0.12.

**Comment by ndwinton** [comment]
Given that the 0.12 release doesn't fix the reliability issues (and may make them slightly worse because of the larger scope of the release), there is little to be gained from an upgrade at this point.

**Comment by hosseinpn** [comment]
Hitting the pause button on this!
