### ISSUE TITLE
Retitle material to be "CKA Refresher"

### ISSUE THREAD

**Issue by ndwinton** [vmware-tanzu-learning/tko-ref-arch-training#38]
**Let us know what feedback you have**

*From the retro of 16 May*

It was felt that at least some of the material within the "Beyond the CKA" section was more "CKA Refresher" than anything new beyond the CKA. Re-titling would help.

**Comment by djschny** [comment]
What about if we just treat the `Kubernetes Core Concepts` courses as the `CKA Refresher` part? That way it promotes reuse across the various subscription goals?

**Comment by djschny** [comment]
Was waiting on the folks going through this to slow down so when things get re-shuffled it doesn't cause noise/confusion. That time is now here.

**Comment by JohnFunk-VMW** [comment]
Can someone compare and contrast the [Kubernetes Core Concepts learning path](https://staging.kubeacademy.fixeldev.com/paths/kubernetes-core-concepts) to the [TKO:Beyond the CKA](https://staging.kubeacademy.fixeldev.com/courses/tko-01-beyond-cka) course.   They look very similar and duplicative to me.  Why do we have both of them?  If they are indeed duplicative should we evaluate deprecating one of them?

They both seem like suitable modules to use if someone needs a refresher on core concepts.  If we use the TKO:Beyond the CKA it make sense to re-name it to "CKA Refresher"

**Comment by djschny** [comment]
> Can someone compare and contrast the [Kubernetes Core Concepts learning path](https://staging.kubeacademy.fixeldev.com/paths/kubernetes-core-concepts) to the [TKO:Beyond the CKA](https://staging.kubeacademy.fixeldev.com/courses/tko-01-beyond-cka) course.

This has been talked about extensively in meetings and Slack. It started out as a subset of material from Kubernetes Core Concepts that was deemed topics that were not covered in CKA material. The last 2 lessons (secrets management and Cluster API came from other areas of KubeAcademy). For example it did not originally include lecture/lab 01/02 but we were asked to include those so it then grew.

> Why do we have both of them? 

A learning path can include existing courses. It can't include other learning paths. It's also apples to oranges, Kubernetes Core Concepts is a *learning path* and TKO: Beyond the CKA is a *course*.

>  If they are indeed duplicative should we evaluate deprecating one of them?

See above and discussion in general. The plan is to no longer have a "Beyond the CKA" course in the learning path. The "Kubernetes Core Concepts" learning path would be there as an optional set of material that could be taken if you need a refresher prior to starting the learning path.

**Comment by JohnFunk-VMW** [comment]
@djschny Thanks for that Summary that brings me current.

**Comment by djschny** [comment]
The Kubernetes Core Concepts learning path courses/lesson in Staging were missing videos, times, tags, graphics. Those have been added as we now point to it.

**Comment by djschny** [comment]
This has been completed - https://staging.kubeacademy.fixeldev.com/courses/tko-01-preparation

* Course renamed to `TKO - Preparation and Prerequisites`
* In course description and in first lesson of README, call outs are made in case a person comes to the course directly and not from via the Learning Path.
* Kubernetes Core Concepts is linked/referenced, but is not included in the learning path.

**Comment by ndwinton** [comment]
I'm happy with the new, trimmed down, section. To set the overall context for that, and the rest of the learning path, I suggest adding something like this to the learning path description, to describe the overall arc of the material:

> The first parts of this learning path introduce or refresh some base concepts fundamental to TKO, including Cluster API and Operators. The "Kubernetes Platform Design" course gives hands-on experience with many of the core ideas and technologies that make up a production Kubernetes platform like TKO. The learning path then looks at each of the specific products and components within TKO in more detail and, finally, moves on to deploying an instance of the TKO reference architecture.
