### ISSUE TITLE
Facilitate pairing by providing visibility of progress

### ISSUE THREAD

**Issue by ndwinton** [vmware-tanzu-learning/tko-ref-arch-training#40]
**Let us know what feedback you have**

*From the retro of 16 May*

Think through ways to expose where people are in the training to enable people to help one another or pair on specific things

**Comment by djschny** [comment]
Note: This is something that more of an internal thing right now, as opposed to something that would be in a public version of the material.

**Comment by djschny** [comment]
This scope is greater than TKO ref arch training and is something that can be handled externally (internal Slack channel for example).
