### ISSUE TITLE
Clarify core vs supporting material and timings

### ISSUE THREAD

**Issue by ndwinton** [vmware-tanzu-learning/tko-ref-arch-training#41]
**Let us know what feedback you have**

*From the retro of 16 May*

Re-evaluate how to clarify reference material vs supporting material, and look into how to define total time for each lesson as a result. ie: Video = 5m, ref material = 10m, total = 15m - Ryan

**Comment by djschny** [comment]
I think the best way to solve both of these is if there is material linked external to the KA platform, then we break it out into a lesson by itself. The links section can then remain for supporting material. This also means the time on the lesson is only for on thing, not more than one.

**Comment by ndwinton** [comment]
In Lesson 06, the blog post could stay within the lesson as it is "supporting material" and timing would be more subjective depending on the reader. But if you wanted to make a general pattern of intro lesson followed by in-depth material then happy with that. All the rest seem good to me.
