### ISSUE TITLE
Lab 01: Cluster Setup -> 1.4 Initialize Cluster:  Calico installation instructions out of date

### ISSUE THREAD

**Issue by jeffjanderson** [vmware-tanzu-learning/tko-ref-arch-training#42]
**Describe the issue**
In Lab 01: Cluster Setup -> 1.4 Initialize Cluster...   when I ran the following instruction, I got an error when deploying Calico:

```
ubuntu@master:~$ kubectl apply -f https://projectcalico.docs.tigera.io/v3.22/manifests/calico.yaml
error: unable to read URL "https://projectcalico.docs.tigera.io/v3.22/manifests/calico.yaml", server reported 404 Not Found, status code=404
```

**To reproduce**
1. Go to `https://j7gmbzbzdeoszrqcb-62179b494c152d6ecdb7c9f0.rp.strigo.io/instructions/lab01/lab01.html` (<--or equivalent URL for a new Strigo session ?)
2. Follow the lab until you get to the mentioned command in section 1.4: Initialize Cluster
3. Observe the error

**Expected behavior**
Calico networking is applied via yaml retrieved from the Calico site

**Additional context -- potential solution**
The doc includes this URL:

```https://projectcalico.docs.tigera.io/v3.22/manifests/calico.yaml```

The problem here in the URL is with the version number... when 3.22 was the latest version, this URL worked.  Once 3.23 came out, the proper URL for 3.22 now includes 'archive' in the path as documented on the Calico site [v3.22 specific doc here](https://projectcalico.docs.tigera.io/archive/v3.22/getting-started/kubernetes/quickstart).

If you click the dropdown in the top right to go to the latest (3.23 as of now), you'll see the URL is documented as:

```kubectl create -f https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml```

...you can see there's no version nor word 'archive' in that URL, as it represents 'latest'.  If the intention is to use latest, it seems using this URL would be the right way to go.  If using a specific version, seems like you need to include the word 'archive' in the URL.

**Comment by djschny** [comment]
Thanks! It looks like if we always use `archive` then it will work. For example even though 3.23 is the latest it still works with archive:

https://projectcalico.docs.tigera.io/v3.23/manifests/calico.yaml

**Comment by djschny** [comment]
kubectl create -f https://projectcalico.docs.tigera.io/archive/v3.23/manifests/tigera-operator.yaml

We'll update the instructions to use `archive` in the URL all the time.

**Comment by jeffjanderson** [comment]
Awesome thank you!

**Comment by ndwinton** [comment]
> kubectl create -f https://projectcalico.docs.tigera.io/archive/v3.23/manifests/tigera-operator.yaml
> 
> We'll update the instructions to use `archive` in the URL all the time.

Agree, it may be a good time to swap to the operator now. I deliberately didn't make that change when updating to use the Tigera URL (as the old Calico ones had stopped working) just to keep it in line with the previous (non-operator) version. Now we're happier that people will be familiar with operators at this point.

**Comment by djschny** [comment]
PR will happen in the specific course repo.
