### ISSUE TITLE
Evaluate material on Wavefront YouTube channel

### ISSUE THREAD

**Issue by ndwinton** [vmware-tanzu-learning/tko-ref-arch-training#43]
**Why would you like this feature?**
It appears that Tanzu Observability (Wavefront) has a whole dedicated youTube channel full of material, which could form the basis of expanded TO training within the TKO path.

**Describe what you'd like to see**
Evaluation of the content there and construction of a learning path using it.

Internal material may cover other issues or cover things in greater depth, but it's good to be able to use public material wherever possible.

**Describe alternatives you've considered**

[This video](https://www.youtube.com/watch?v=b3UqKC10HnA) on Elastic Observability (found by @djschny) does a good job of positioning observability for K8s in general, and has a relatively brief but well thought-out demo. It's a different product, but may be a useful comparison.

**Comment by mrporcles** [comment]
There is a [wavefront fundamentals training](https://youtube.com/playlist?list=PLPGZsvbdUCi4UvTy3WLtqfUXw_P-iKLKP) playlist on youtube which is less marketing fluff and more detailed technical overview/content. Problem here is that although this is hosted on youtube, it is an unlisted playlist with the videos marked as private. From previous discussions this has not been made public for a reason and may have been used previously as official training for wavefront customers with it only being made available to them as needed.

**Comment by djschny** [comment]
Great find @mrporcles. A few things come to my mind from what I see at the playlist and with your remarks above that we could consider.

1. As an interim solution the videos could be placed into KA staging and we keep them private until a better solution.
1. We look to see if a subset of the videos are "safe" to be public.
1. Do you recall who was in your previous discussion that we could reach back out to and ask about making it public safe? Given it the videos are 2 years old might be a good time for them to update them anyway to reflect functional and UX changes. 

Thoughts?

**Comment by mrporcles** [comment]
No commitment on public usage question once I described how we wanted to use the content. Bumped today and added @JohnFunk-VMW and @hosseinpn for visibility and potential higher chain follow up

**Comment by JohnFunk-VMW** [comment]
The last message from Bahubali Shetti, Director, Tanzu SaaS Value Engineering says yes we can the videos.  
https://vmware.slack.com/archives/C014P2JME1L/p1656577520403339

I recommend still reviewing the material for anything we think is not appropriate to share, such as talk about our go to market strategy etc.  If we find those sort of things we can work on ways to edit them out.

**Comment by mrporcles** [comment]
Going through all the content provided the Youtube playlist seems to be the one whose content is the best fit in terms of structure and level of detail. These were designed for public consumption so after review there is no content contained therein that is not appropriate to share as per your concern above. Based on this being the best option - a couple of questions @JohnFunk-VMW 

- Do we want to try and source the originals of these videos so we can self host and brand with a view to the course being made public?
- Should we try and work with the TO marketing team to get these updated to match current UI and feature set?

**Comment by djschny** [comment]
@mrporcles We can also just download then from YouTube and then upload to Vimeo. I have a firefox plugin I've used before if we need to. While in parallel see if original videos can be found.

**Comment by mrporcles** [comment]
@djschny @ndwinton I have created a course for the Tanzu Observability Fundamentals content [here](https://staging.kubeacademy.fixeldev.com/courses/tanzu-observability-fundamentals). Please review and let me know if any issues. The aim is to add this to the end of the TKO learning path as an optional module and remove the current link out to the Youtube playlist earlier in the path.

**Comment by mrporcles** [comment]
Added the Tanzu Observability Fundamentals Course to the end of the TKO learning path. Removed the TO Product Usage lesson as it is now redundant and expanded the TO Product lesson verbage to mention the optional TO Fundamentals course for more advanced knowledge.
