### ISSUE TITLE
Calico Install Instructions no longer work

### ISSUE THREAD

**Issue by huninmunin** [vmware-tanzu-learning/tko-ref-arch-training#46]
**Describe the issue**
A clear and concise description of what the problem is.

Calico fails to install using the provided instructions.

Class: Kubernetes Platform Design
Step 1.4 Initialize Cluster

The following command did not work, since the URL now returns raw HTML: 
```
kubectl apply -f https://projectcalico.docs.tigera.io/v3.22/manifests/calico.yaml
```

**To reproduce**
1.  Navigate to [manifest file](https://projectcalico.docs.tigera.io/v3.22/manifests/calico.yaml)
2. See raw HTML instead of expected YAML

**Expected behavior**
Expected Calico to be installed. 

**Additional context**
I found that the following commands installed Calico, and I was able to continue with the lab. 

Link: 
https://projectcalico.docs.tigera.io/getting-started/kubernetes/quickstart

```
Install the Tigera Calico operator and custom resource definitions.

kubectl create -f https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml

Install Calico by creating the necessary custom resource. For more information on configuration options available in this manifest, see [the installation reference](https://projectcalico.docs.tigera.io/reference/installation/api).

kubectl create -f https://projectcalico.docs.tigera.io/manifests/custom-resources.yaml

```

**Comment by djschny** [comment]
See https://github.com/vmware-tanzu-learning/tko-ref-arch-training/issues/42
