### ISSUE TITLE
Create lecture/lab on Service Mesh

### ISSUE THREAD

**Issue by ndwinton** [vmware-tanzu-learning/tko-ref-arch-training#49]
**Why would you like this feature?**
If this solves a problem for you please give a clear and concise description of what the problem is, for example, "I'm always frustrated when ..."

**Describe what you'd like to see**
Content should include:
* Intro to service mesh concepts
* Use cases
   * mTLS
   * Monitoring/interception
   * Multi-cluster federation 
* Common architecture (e.g. control/data plane, use of sidecars)
* Advice about what can happen when you plugin service mesh and it goes wrong (excluding namespaces, etc.)

Lab probably using Linkerd

**Describe alternatives you've considered**
Istio/Envoy are the underpinnings of Tanzu Service Mesh, but are complex. Linkerd is a much simpler technology to introduce the ideas of SM.

**Comment by ndwinton** [comment]
[Open Service Mesh](https://openservicemesh.io) might be an alternative to consider for the lab. It uses Envoy as the proxy, which is closer to Tanzu Service Mesh, but is possibly simpler than Istio.

**Comment by ndwinton** [comment]
Experimented with OSM and the [Yelb application](https://github.com/mreferre/yelb). Install was simple but applying OSM to Yelb broke the application. It is not clear why, it may be something to do with the use of NodePort because slightly better results were seen from port-forwarding.

Results with Linkerd were much better, including the use of "tapping" to intercept traffic and the visualisation dashboard. However, Linkerd recognises Postgres and Redis as protocols that it can't immediately handle, so visualisation of those isn't as rich. It also seems that doesn't detect traffic to the `yelb-appserver` correctly. This may be because it's using port 4567 which can be associated with MySQL?

**Comment by djschny** [comment]
Thanks for all the investigation on this and various options. Some things come to mind:

This lab will serve one of two purposes:

1. To get folks experience installing and using TSM outside of the larger TKO deployment
1. To get folks experience with service mesh in general and the nuisances and details around it.

If it is `#2` then the nuisances talked about above can be worked into the lab intentionally for example.

**Comment by ndwinton** [comment]
Further investigation done of Linkerd, Open Service Mesh and Istio.

Initial Istio usage can be simplified sufficiently so that we may as well use it rather than introduce a different technology.

The Linkerd "Emojivoto" demo application is attractive because it has built-in traffic generation (and is fun!), but the Istio "bookinfo" demo is probably fine too.

A few notes from the experiments follow ...

### Installing Emojivoto

On desktop (this can probably be added to the initialisation script)

```
sudo apt update
sudo apt install fonts-noto-color-emoji
sudo apt reinstall google-chrome-stable
```

On master:

```
kubectl apply -k github.com/BuoyantIO/emojivoto/kustomize/deployment
kubectl patch -n emojivoto svc web-svc -p '{"spec":{"type":"NodePort"}}'
echo http://master:$(kubectl get -n emojivoto svc web-svc -o jsonpath='{.spec.ports[0].nodePort}')
```

### Istio install

```bash
curl -L https://istio.io/downloadIstio | sh -

sudo install istio-1.*/bin/istioctl /usr/local/bin

istioctl install -y
```

Output is:
```
✔ Istio core installed                                                                                                                                                                                                                                                       
✔ Istiod installed                                                                                                                                                                                                                                                           
✔ Ingress gateways installed                                                                                                                                                                                                                                                 
✔ Installation complete                                                                                                                                                                                                                                                      Making this installation the default for injection and validation.
```

### Monitoring traffic inside the container

The `nicolaka/netshoot` container image has a slew of useful network tools, so we can inject it into the pod using `kubectl debug` ...

```
kubectl debug -n emojivoto -it web-f568dd769-4nncs --image nicolaka/netshoot -- /bin/bash
```

Once in there, `tshark` can show the traffic:

```
bash-5.1# tshark port 8080 | grep HTTP
Capturing on 'eth0'
 ** (tshark:84) 11:41:44.302646 [Main MESSAGE] -- Capture started.
 ** (tshark:84) 11:41:44.302694 [Main MESSAGE] -- File: "/tmp/wireshark_eth0U90JO1.pcapng"
    1 0.000000000 192.168.189.72 → 192.168.189.71 HTTP 271 GET /api/list HTTP/1.1 
   11 0.001514293 192.168.189.71 → 192.168.189.72 TCP 4162 HTTP/1.1 200 OK  [TCP segment of a reassembled PDU]
   16 0.001578109 192.168.189.71 → 192.168.189.72 HTTP/JSON 627 HTTP/1.1 200 OK , JavaScript Object Notation (application/json)
   18 0.002071659 192.168.189.72 → 192.168.189.71 HTTP 289 GET /api/vote?choice=:doughnut: HTTP/1.1 
38    33 0.003925954 192.168.189.71 → 192.168.189.72 HTTP/JSON 259 HTTP/1.1 500 Internal Server Error , JavaScript Object Notation (application/json)
   42 1.006404508 192.168.189.72 → 192.168.189.71 HTTP 271 GET /api/list HTTP/1.1 
   50 1.007924278 192.168.189.71 → 192.168.189.72 TCP 4162 HTTP/1.1 200 OK  [TCP segment of a reassembled PDU]
   53 1.007990736 192.168.189.71 → 192.168.189.72 HTTP/JSON 627 HTTP/1.1 200 OK , JavaScript Object Notation (application/json)
   56 1.008328801 192.168.189.72 → 192.168.189.71 HTTP 296 GET /api/vote?choice=:woman_shrugging: HTTP/1.1 
77    71 1.010206112 192.168.189.71 → 192.168.189.72 HTTP 141 HTTP/1.1 200 OK 
^C
```

**Comment by djschny** [comment]
Awesome!

Agreed on might as well use istio given the statements above.

On a side note if we use `kubectl debug`, we'll need to temporarily explain it until we add it's use into the Foundations/Ops courses IMO.

So the lab would go something like the following?

* Show the app we're using and why we chose it. 
* Show packet capture without istio
* Uninstall the app
* Explain what we're trying to accomplish with Istio and why we need it
* install istio
* Install the app
* package capture again to show difference

**Comment by ndwinton** [comment]
That's much of it. I've played with the Kiali dashboard for Istio too now – pretty nice, and similar in spirit to TSM and other similar offerings. So, I think the lab goes like this:

* Part 1 - mTLS
    * Show the app and why we chose it
    * Show packed capture without Istio
    * Install Istio
    * (Show app still working - no initial impact)
    * Enable Istio on the app namespace
    * Redploy the app
    * Show app still working
    * Packet capture again to show the difference
    * Explore the side-car containers

* Part 2 - Traffic tracing and dashboard
    * Install Kiali etc. and run dashboard
    * Explore some aspects of dashboard (network graphs, traces, stats)

* Part 3 - Additional configuration
    * Look at Istio CRDs
    * Istio ingress vs others
    * (Possibly) Traffic splitting
    * What could possibly go wrong ...

**Comment by ndwinton** [comment]
Looking at the Emojivoto code it appears that a later version (v12, available in the registry) has additional configuration on the `voting` app to allow it to fail on the doughnut emoji on an intermittent, rather than continual, basis. There are environment variables `FAILURE_RATE` (a value between 0.0 and 1.0, default 0.0) and `ARTIFICIAL_DELAY` (default 0ms, added to each service call). This makes it easier to demonstrate, for example, traffic splitting and retry capabilities.

One question arises: should we fork and build our own version to maintain control over the image registry?

**Comment by ndwinton** [comment]
I've added a new folder to GDrive ([k8s-platform-design-extended](https://drive.google.com/drive/folders/1k9GJVWYEUP8Gg16wZj5aCcSEyPQNbi7p?usp=sharing)) with a first version of slides for a Service Mesh lecture.

**Comment by ndwinton** [comment]
I've pushed a version of the service mesh lab to https://github.com/vmware-tanzu-learning/k8s-platform-design-extended

This is essentially "part 1" of what is turning into something of a magnum opus!

@djschny @mrporcles - I'd appreciate it if you had a few mins were able to take a look at what's there and give any initial thoughts before I go plunging ever onwards.

You can run the lab using the current K8s Platform Design Strigo setup or, I believe, it should be possible using Kind/Minikube too (with a bit of mucking with port-forwarding).

**Comment by djschny** [comment]
Great job @ndwinton and awesome work so far. I like the use of prompting people to investigate and solve a problem with the hidden answer, inspect traffic, and note box disclaimers. To your request about initial thoughts:

* As I started the lab and showed the demo application prior to a service mesh installed, I was expecting an explanation of **why** a service mesh is needed to make the demo application work. And even by the time the lab ended, I was left still wondering **why* the service mesh was needed for the demo application.
* A quick service mesh overview/reference section at the beginning may be helpful as well.

**Comment by ndwinton** [comment]
Thanks @djschny – in this case more of the "why" and "overview" is in the lecture material (slides are in the `docs` directory). However, if we are going to go with the "lab first" approach at the moment, I'll add some stuff in. Probably no bad thing to reiterate it anyway.

**Comment by djschny** [comment]
> in this case more of the "why" and "overview" is in the lecture material (slides are in the docs directory).

Awww I just took a look at those, thanks!

> in this case more of the "why" and "overview" is in the lecture material

I agree with that for the conceptual, however usually the lab talks implementation specifics, so for example, specifically why the demonstration app ([Emojivoto](https://github.com/BuoyantIO/emojivoto)) requires a Service Mesh to work.

**Comment by ndwinton** [comment]
I've added a little more on that, pointing out that Emojivoto does not need (or know about) a service mesh. It's all about enhancing app functionality with a mesh. But there's probably more to do.

**Comment by ndwinton** [comment]
Content is now essentially complete and has been pushed to the PDX repo. I'm now working on a version of Lab 01 to do the intro and cluster setup.

**Comment by djschny** [comment]
> I've added a little more on that, pointing out that Emojivoto does not need (or know about) a service mesh.

Sorry for not catching this in earlier discussion, but I don't think the app is a good fit if it won't work properly without a Service Mesh and will minimize the goal we're trying to accomplish about showing an example of why a Service Mesh is needed.

**Comment by ndwinton** [comment]
Sorry if I wasn't clear there but Emojivoto definitely **does not need** a service mesh to work. As I said, there is no mesh-dependent code whatever in it. It is fully functional without the mesh, and the first part of the lab shows that.

So, it demonstrates very well the features that you can add to such an application (secure comms, observability and resilience) transparently and incrementally without having to change the application at all.

**Comment by mrporcles** [comment]
Good work @ndwinton. Great content and good flow. I have put in a [PR](https://github.com/vmware-tanzu-learning/k8s-platform-design-extended/pull/1) with some minor changes to the material. I agree with @djschny in that it would be good to have an overview of what a service mesh can provide and how it relates to the lab. I would also add a Summary/Takeaways section at the end of the lab to reiterate learnings.

**Comment by ndwinton** [comment]
Thanks @mrporcles – I will add overview and summary (and make the learning objectives clear).

**Comment by ndwinton** [comment]
@djschny @mrporcles – I have now added some content to top and tail the lab. Let me know if this meets your needs.

**Comment by djschny** [comment]
> I have now added some content to top and tail the lab. Let me know if this meets your needs.

Looks great. Refinements can happen over time too and based upon feedback. This works great too if a person comes to the lab and skipped the lecture.

**Comment by mrporcles** [comment]
LGTM 👍

**Comment by ndwinton** [comment]
Available in development. Awaiting remainder of course for go live.
