### ISSUE TITLE
Add hyperlink to Spring Pet Clinic to Course 5, Lesson 2

### ISSUE THREAD

**Issue by ChristmasTaco** [vmware-tanzu-learning/tko-ref-arch-training#51]
**Why would you like this feature?**
We ask users to deploy the Spring Pet Clinic app as part of the Acceptance Criteria, but we don't hyperlink to the git repo.

**Describe what you'd like to see**
In the first bullet of the Acceptance Criteria where we note "Spring Pet Clinic test app", please make that text a hyperlink to: https://github.com/spring-projects/spring-petclinic
<img width="1198" alt="Deploy_TKO_on_AWS_-_TKO__Deploy_a_TKO_Reference_Architecture_-_KubeAcademy" src="https://user-images.githubusercontent.com/12519848/173448965-13d744f7-a09c-4360-8620-1db7076f9874.png">

**Comment by mrporcles** [comment]
Complete. Updated [lesson](https://staging.kubeacademy.fixeldev.com/courses/tko-deploy-a-tko-reference-architecture/lessons/deploy-tko-on-aws)

**Comment by djschny** [comment]
Thanks.
