### ISSUE TITLE
deploy Calico link not found

### ISSUE THREAD

**Issue by surajash** [vmware-tanzu-learning/tko-ref-arch-training#57]
**Describe the issue**
deploy Calico not working
 kubectl apply -f https://projectcalico.docs.tigera.io/v3.22/manifests/calico.yaml

**To reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/37057762/179266195-88b5fd40-ade8-48fa-8ac5-aa8d18350593.png)
![image](https://user-images.githubusercontent.com/37057762/179266330-8fe66b41-c3e7-4566-b607-b240ea267a49.png)

**Additional context**

**Comment by djschny** [comment]
Hi @surajash thanks for taking the time to report this and sorry for the inconvenience. We have a fix in but it hasn't been deployed yet, working on that now.

Please use URL `https://projectcalico.docs.tigera.io/archive/v3.22/manifests/calico.yaml` instead until we get the lab instructions updated in the environment.

**Comment by djschny** [comment]
New labs launched will see the update.
