### ISSUE TITLE
TKG Tips

### ISSUE THREAD

**Issue by djschny** [vmware-tanzu-learning/tko-ref-arch-training#6]
As found while @ndwinton was working with OIDC configuration TKG against Okta:

* The list of scopes to request is comma separated (in the install UI) - but you have to make sure there are no spaces
* I accidentally pasted the wrong values for client ID and secret into the config screens. I tried uninstalling/reinstalling the pinniped package, after changing the values in necessary config … However, there is actually another package (the tanzu-addons-manager) which maintains the other packages. This meant that as soon as I’d uninstalled the package, it reappeared again! In the end, I found a secret in the tkg-system space, <mgmt-cluster-name>-pinniped-addon, which I had to change. I then uninstalled pinniped again and let the addon manager recreate it.
* You can disable the pinniped login from trying to automatically start a browser (if it’s a headless system) and instead let it print the URL. You can visit that and complete the login … but … the last part of the login attempts to pass the final token back by accessing a localhost URL. I had to background the command that caused the login, curl that URL, and then things completed. Obviously the headless use case needs some work. It’d be pretty smooth for normal browser-based used however

* Further update on the Pinniped side ... I looks like the headless login scenario is much better addressed in Pinniped 0.10.0 onwards. TKG 1.4 uses Pinniped 0.4.4, while TKG 1.5 uses 0.12.0. I've yet to check which version is in TCE, but it should be pretty up to date.

**Comment by hosseinpn** [comment]
Neil incrporated this into the H2O / pinniped lab
