### ISSUE TITLE
Reduce pre-req content (was "reduce fatigue:)

### ISSUE THREAD

**Issue by djschny** [vmware-tanzu-learning/tko-ref-arch-training#60]
According to tracking data it appears people start out with the best of intentions and we see decent numbers around the first two courses. However after the Operator course very few people (20% roughly) actually continued with the rest of the material or launched the lab for the Platform Design Course.

Some thoughts @ndwinton and I had in chatting were:

* Swap KPD and Operators Course
* Remove Operators Course and instead just have a singe lesson on Operators in the first course
* See if we can introduce a two lesson combo in the first course where first lesson is lecture and second is a lab

**Comment by djschny** [comment]
@ndwinton are you OK with moving forward with the second bullet above?

> * Remove Operators Course and instead just have a singe lesson on Operators in the first course

I think it's the easier and simplist for right now.

**Comment by hosseinpn** [comment]
The second option seems to be the best way to introduce learners to Operators - we still have a full course on Operators that learners can refer to (as discussed with @djschny on Friday Sep 9). @ndwinton Are you okay with option 2 as the solution for our first release?

**Comment by ndwinton** [comment]
Yes, I agree. I'd already made the following suggestion in the "production to-do list" issue:

> Learning from the partner cohort indicates that many people gave up at the end of this course, which is more detailed than necessary for the TKO path. Maybe create a cut-down version combining lessons 1-3?

So, yes, a single lesson is fine by me. I thank that really leaves us with two pre-req lessons:

* Operators
* Cluster API

The other lesson in the pre-req part, on secrets management, isn't really needed for TKO as there is nothing in the TKO offering that deals with that.

**Comment by ndwinton** [comment]
I suggest we use the following lecture for Operators: https://kube.academy/courses/building-application-platforms-with-kubernetes/lessons/operators. It's a pity he's obviously reading the script, but it's still decent intro content.

Rather than the "Secrets Management" lecture from the "Building Application Platforms with Kubernetes", I suggest we use the *Certificate* Management lecture, as that introduces `cert-manager`.

**Comment by ndwinton** [comment]
I've updated the pre-reqs course as outlined above, and removed the "Introduction to Operators" course from the learning path.

**Comment by djschny** [comment]
LGTM.
