### ISSUE TITLE
Not able to login for the labs in the course - https://staging.kubeacademy.fixeldev.com/paths/tanzu-kubernetes-operations

### ISSUE THREAD

**Issue by parhos** [vmware-tanzu-learning/tko-ref-arch-training#61]
**Describe the issue**
saravanan.veerappan@mphasis.com -> this is the ID i am using to login for the lab practice.. but it says like below.. 
**"Unfortunately, we cannot connect you to this training environment.
This could happen if you're not enrolled in the course, or if you signed-in to Strigo with a different address than the one you enrolled in this course with.
If saravanan.veerappan@mphasis.com is the address you used to enroll to the course, please contact your course provider, as they can best help you resolve this issue."**
 

**To reproduce**
NA

**Expected behavior**
allow me to login to lab practice

**Screenshots**
NA
**Additional context**
AN

**Comment by djschny** [comment]
Closing as most likely resolved by guidance.
