### ISSUE TITLE
Release Tanzu Observability Fundamentals course in production Kube Academy

### ISSUE THREAD

**Issue by mrporcles** [vmware-tanzu-learning/tko-ref-arch-training#69]
Need to get our course content out in the public. Acknowledging the fact that TO is product specific and KA is the only platform available to us at this point.

**Comment by mrporcles** [comment]
Course has been created in draft [here](https://kube.academy/courses/tanzu-observability-fundamentals)

**Comment by djschny** [comment]
Can we please review in Staging first and then we will migrate the courses all at once?

Having coordinated/known changes happening in production should be avoided.

**Comment by mrporcles** [comment]
Yip I requested a review on this a couple of weeks ago via this [issue](https://github.com/vmware-tanzu-learning/tko-ref-arch-training/issues/43). Had no feedback so assumed it was ok to move forward. If not @djschny @ndwinton can you please review the course in [staging](https://staging.kubeacademy.fixeldev.com/courses/tanzu-observability-fundamentals) and provide feedback.

As there is no real dependency between this and the other courses I don't see an issue promoting it in isolation if it is ready to go. Otherwise aren't we just holding up progress for other work where we aren't necessarily sure of timelines?

**Comment by ndwinton** [comment]
Paul - my apologies for not reviewing this sooner.

Overall, a nice job of bringing it into KA. I've got just a couple of minor suggestions to further improve it:

1. In the text to the very first lesson, explain why you refer to **Tanzu Observability** but all the videos talk about **Wavefront**. Yes, we know the answer, but it might be confusing to people who don't! And it looks like the [Aria-rebranded page](https://tanzu.vmware.com/aria-operations-for-applications) has now gone live too.
2. It would be useful to add links to each video to relevant product pages (if you can find any easily).

That's it!

**Comment by mrporcles** [comment]
Suggested changes from @ndwinton have been included in both the staging and draft production versions of the course. This should be good to go for promotion to live in prod.

- [Staging](https://admin.staging.kubeacademy.fixeldev.com/courses/tanzu-observability-fundamentals)
- [Production](https://kube.academy/courses/tanzu-observability-fundamentals)

**Comment by ndwinton** [comment]
Course is now live!
