### ISSUE TITLE
add carvel lab once available

### ISSUE THREAD

**Issue by djschny** [vmware-tanzu-learning/tko-ref-arch-training#7]
We included a video/demo as part of #1 , however should add in the lab once available.

**Comment by djschny** [comment]
@ndwinton also noted that last week a video and blog on YTT overlays was released:

https://carvel.dev/blog/primer-on-ytt-overlays/

**Comment by ndwinton** [comment]
There is also an interactive "playground" with a step-by-step tutorial at https://carvel.dev/ytt/#playground. We should review this for suitability.

**Comment by hosseinpn** [comment]
This is being tracked in the TAP backlog. Potentially we want to invest more time in separating TAP and Carvel.
