### ISSUE TITLE
TKO Learning Path intro text needs to be revised

### ISSUE THREAD

**Issue by ndwinton** [vmware-tanzu-learning/tko-ref-arch-training#71]
**Describe the issue**
The current text is very specific to the internal/partner cohorts. It needs to be revised for public release.

**Comment by djschny** [comment]
Revised:

---

The material in this Learning Path is to help you prepare to build and use the [Tanzu Kubernetes Operations](https://docs.vmware.com/en/VMware-Tanzu/services/tanzu-reference-architecture/GUID-reference-designs-index.html) reference architecture solutions. Important items to note before starting:

* This material assumes you have a CKA level knowledge/experience of Kubernetes. Ideally you have successfully passed your [CKA](https://www.cncf.io/certification/cka/).
* If you are not comfortable/fluent with you Kubernetes knowledge and tasks beyond the basics (storage, debugging, networking, etc.) then we recommend taking the [Kubernetes Core Concepts learning path](/paths/kubernetes-core-concepts) here on KubeAcademy.

**Comment by djschny** [comment]
Update is live - https://staging.kubeacademy.fixeldev.com/paths/tanzu-kubernetes-operations
