### ISSUE TITLE
Vimeo Pro Subscription expiry

### ISSUE THREAD

**Issue by ndwinton** [vmware-tanzu-learning/tko-ref-arch-training#82]
The one month grace on the Vimeo Pro subscription has expired. KubeAcademy videos have become inaccessible. Urgent action needed!

**Comment by djschny** [comment]
This has purchased earlier, but Vimeo support unfortunately had misguided and the purchase applied to my personal account. I had engaged with them again, they refunded that purchase and it was rebought on the VMware account.

It should be good.
